name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.TOKEN}}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
      - name: Use GitHub Token
        run: echo "Using the GitHub Token"
        env:
          token: ${{secrets.TOKEN}}
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update
      - name: Install Dependencies
        run: npm ci
      - name: Authenticate with GitHub
        run: |
          git config --global user.email "k223kim@uwaterloo.ca"
          git config --global user.name "Kaeun Kim"
          git remote set-url origin https://k223kim:${{secrets.TOKEN}}@github.com/k223kim/second-brain-private.git
          rm content
          git mv second-brain-private content
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.TOKEN}}
